### ISSUE TITLE
how can i get the fully qualified property name in callback even

### ISSUE THREAD

**Issue by tariqmatech** [melanke/Watch.JS#119] opened 2017-11-15 20:57 UTC
trying to use if for two way binding, the beautiful thing about this one is I can use my ajax response as is. don't want to add bulky frameworks for two way binding. 

please let me know how can i get the fully qualified property name in callback event so i can update DOM objects in my html with the newly modified value.

**Comment by qualityking** [comment] 2017-12-01 12:34
hi @tariqmatech  i am trying the same and looking for the full property name myself, anyluck ?

**Comment by melanke** [comment] 2018-03-15 23:27
Duplicate of #77

**Closed by melanke** 2018-03-15 23:27 UTC
Labels: enhancement
